config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def show
    @flat = Flat.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<body>

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="/">Simple Airbnb</a>
  </nav>
  <div class='container mt-3'>
      <div class='row'>
        <div class='col-12'>
          <h3>All flats (<%= @flats.size %>)</h3>
        </div>
      </div>
      <div class='row'>
          <% @flats.each do |flat| %>
          <div class="col-4">
            <div class='flat-card'>
              <div class='content-card'>
                <h4><%= flat.name %></h4>
                <p><%= flat.description %></p>
                <p><%= flat.address %></p>
                <p>$<%= flat.price_per_night %></p>
                <p><i class="fas fa-users"></i><%= flat.number_of_guests %></p>
              </div>
              <div class='button-card'>
                <%=link_to "More Info", flat_path(flat)%>
              </div>
            </div>
          </div>
          <% end %>
      </div>
  </div>
</body>

app/views/flats/show.html.erb
<body>

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="/">Simple Airbnb</a>
  </nav>
  <div class='container mt-3'>
      <div class='row'>

      </div>
      <div class='row'>
          <div class="col-4">
            <div class='flat-card'>
            <div class='content-card'>
              <h4><%= @flat.name %></h4>
              <p><%= @flat.description %></p>
              <p><%= @flat.address %></p>
              <p>$<%= @flat.price_per_night %></p>
              <p><i class="fas fa-users"></i><%= @flat.number_of_guests %></p>
            </div>
              <div class='button-card'>
                <%=link_to "back", flats_path%>
              </div>
          </div>
      </div>
  </div>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
 <!-- ... -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <%= yield %>
  </body>
</html>